### PR TITLE
DBZ-8025: First Pass at adding Observed Generation

### PR DESCRIPTION
**Pull request by ryanvanhuuksloot**
Attempting a first pass at adding observed generation to the `status.observedGeneration` spec.

I couldn't figure out how to test this though. I built and loaded the jar(s) into my operator but it wouldn't pick up the latest code - not even log lines I tested for debugging.

I also realize that I need to add tests - but since more than just `Conditions` now are changing in status, I think it is worth a discussion on how the status should be handled.

### CODE REVIEW

**Comment by jcechace** [comment]
LGTM 

Regarding testing: this is also something we need to work on. Technically right now tests in the core module are set to only use api server. I intend to switch that to full kind and have some base tests there. 

As for building -- I think a contributor guide should help. Since we are releasing also helm charts and OLM bundles the process is a bit complex -- while the operator is technically just the core module, the final build is driven by the dist module. 

To make things worse, I probably have a bit incorrect quarkus setup -- which results in  devmode having troubles picking up code changes in other modules than core. I intend to fix that as well for 3.0 after consulting a friend.

**Comment by ryanvanhuuksloot** [comment]
Sounds good - no rush on merging this - we aren't blocked right now. I'm just looking at removing future blockers early.

Happy to wait for a contributor guide and be the first drive it.

**Comment by jcechace** [comment]
@ryanvanhuuksloot  if you consider this done I'm happy to merge this.

**Comment by ryanvanhuuksloot** [comment]
I want to test it fully in our working environment first. I think something is missing/misconfigured because it doesn't work as I thought it would in my testing environment. 
I applied the new CRD, a new operator image with the new core and api jar. Yet seems to fail writing the status. It doesn't look like a permission error.

I was hoping for some guide to deploy operator changes to validate that it is the code and not how I deployed the new operator code.

**Comment by jcechace** [comment]
I did some preliminary testing and it seems to work fine. Thanks for the contribution!

**Pull request merged**
